Fix web buttons
DenisovAV/recyclo pull request #20
Opened 2024-04-20 10:04 UTC by PavlyukovYegor

Fix buttons for app download
Change content for Google and Apple wallet

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-04-20 13:35 UTC, nikitaessen approved these changes

2024-04-21 09:59 UTC, DenisovAV commented on assets/images/2x/wallet_screen.png
Wrong design

2024-04-21 09:59 UTC, DenisovAV requested changes
Change images to correct

2024-04-21 10:06 UTC, DenisovAV approved these changes

2024-04-21 10:06 UTC, merged